### ISSUE TITLE
Functionality to estimate hazards 

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#106] opened 2022-04-13 00:06 UTC
When we adopted rigr from uwIntroStats, we jettisoned Cox models functionality in order to focus on more widely used (or urgently needed) methods. 

However, many of our courses would benefit from Cox models in rigr (eg., 515/518 with Willis and 513 with May). This issue serves to document that need. 

Note that there is legacy code that could be built upon to do this.

**Comment by adw96** [comment] 2022-04-13 00:06
In the meantime, coxrobust::coxr can give you robust standard errors for hazards.

**Comment by adw96** [comment] 2022-09-07 23:46
@yiqunchen Are we ready to close this?

**Comment by yiqunchen** [comment] 2022-09-08 00:43
closing this since rigr supports hazards regression now -- discussions on related improvements (eg enabling polynomial and centering) should be directed to https://github.com/statdivlab/rigr/issues/121

**Closed by yiqunchen** 2022-09-08 00:43 UTC
Labels: enhancement
